
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "gemini-api-connector" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "gen-lang-client-0592741070"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "openai-api-key" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "gen-lang-client-0592741070"
  name        = "openai-chatgpt-api-key"
  secret_data = "YOUR_OPENAI_API_KEY_HERE"
  labels = {
    app = "ai-orchestrator"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "orchestrator-lb-global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.1.0"
  name          = "ai-agent-orchestrator-frontend"
  project_id    = "gen-lang-client-0592741070"
  url_map_input = module.orchestrator-lb-global-lb-backend.backend_service_info
  labels = {
    app = "ai-orchestrator"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "orchestrator-lb-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.1.0"
  name       = "ai-agent-orchestrator-backend"
  project_id = "gen-lang-client-0592741070"
  serverless_neg_backends = [{
    region          = module.ai-agent-orchestrator.location
    service_name    = module.ai-agent-orchestrator.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  health_check = {
    port         = 8080
    request_path = "/health"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "orchestrator-db-postgresql" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.1"
  project_id                  = "gen-lang-client-0592741070"
  region                      = "us-central1"
  name                        = "ai-agent-orchestrator-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-custom-2-7680"
  deletion_protection_enabled = false
  disk_autoresize             = true
  disk_size                   = 50
  user_labels = {
    app = "ai-orchestrator"
  }
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  ip_configuration = {
    ipv4_enabled    = true
    private_network = "projects/gen-lang-client-0592741070/global/networks/default"
  }
  iam_users = [{
    email = module.ai-agent-orchestrator.service_account_id.email
    id    = module.ai-agent-orchestrator.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "orchestrator-db-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "gen-lang-client-0592741070"
  name        = "ai-agent-orchestrator-db-credentials"
  secret_data = module.orchestrator-db-postgresql.generated_user_password
  labels = {
    app = "ai-orchestrator"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "orchestrator-cache-redis" {
  source             = "github.com/terraform-google-modules/terraform-google-memorystore?ref=v15.2.0"
  project_id         = "gen-lang-client-0592741070"
  region             = "us-central1"
  name               = "ai-agent-orchestrator-cache"
  tier               = "STANDARD_HA"
  memory_size_gb     = 2
  redis_version      = "REDIS_7_2"
  connect_mode       = "PRIVATE_SERVICE_ACCESS"
  read_replicas_mode = "READ_REPLICAS_ENABLED"
  replica_count      = 1
  labels = {
    app = "ai-orchestrator"
  }
  auth_enabled            = true
  transit_encryption_mode = "DISABLED"
  persistence_config = {
    persistence_mode    = "RDB"
    rdb_snapshot_period = "ONE_HOUR"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "user-tier-config-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "gen-lang-client-0592741070"
  name        = "ai-agent-orchestrator-user-tier-config"
  secret_data = "{\\\"free_tier\\\":{\\\"max_tokens\\\":500,\\\"model_version\\\":\\\"basic\\\"},\\\"paid_tier\\\":{\\\"max_tokens\\\":4000,\\\"model_version\\\":\\\"advanced\\\"}}"
  labels = {
    app = "ai-orchestrator"
  }
  depends_on = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "deepseek-api-connector" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "gen-lang-client-0592741070"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "ai-agent-orchestrator" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.2"
  project_id                    = "gen-lang-client-0592741070"
  location                      = "us-central1"
  service_name                  = "ai-agent-orchestrator"
  description                   = "El servicio central que orquesta la interacción entre Gemini, ChatGPT y DeepSeek. Gestiona la lógica de refinamiento, el contexto de la conversación, la adaptación de parámetros por nivel de usuario y cifra/descifra las claves API de los usuarios (utilizando Cloud KMS a nivel de código) antes de almacenarlas en PostgreSQL."
  containers                    = [{"env_vars" = merge({"orchestrator_db_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.orchestrator-db-postgresql.instance_connection_name, "orchestrator_db_postgresql_CLOUD_SQL_DATABASE_HOST" = module.orchestrator-db-postgresql.instance_first_ip_address, "orchestrator_db_postgresql_CLOUD_SQL_DATABASE_NAME" = module.orchestrator-db-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME}, {"orchestrator_cache_redis_REDIS_AUTH_STRING" = module.orchestrator-cache-redis.auth_string, "orchestrator_cache_redis_REDIS_HOST" = module.orchestrator-cache-redis.host, "orchestrator_cache_redis_REDIS_PORT" = module.orchestrator-cache-redis.env_vars.REDIS_PORT}), "container_image" = "gcr.io/cloudrun/hello", "env_secret_vars" = merge({"openai_api_key_SECRET" = module.openai-api-key.env_vars.SECRET}, {"orchestrator_db_secret_SECRET" = module.orchestrator-db-secret.env_vars.SECRET}, {"user_tier_config_secret_SECRET" = module.user-tier-config-secret.env_vars.SECRET})}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/redis.editor"], ["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor", "roles/aiplatform.user", "roles/cloudsql.client", "roles/cloudkms.cryptoKeyEncrypterDecrypter"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 1
  }
  service_labels = merge({"gemini_api_connector_vertex-ai" = "true"}, {"deepseek_api_connector_vertex-ai" = "true"}, {"app" = "ai-orchestrator"})
  template_scaling = {
    min_instance_count = 0
  }
  service_account = "ai-agent-orchestrator-sa@gen-lang-client-0592741070.iam.gserviceaccount.com"
  depends_on      = [module.project-services-gen-lang-client-0592741070, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.3.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.orchestrator-lb-global-lb-frontend.apphub_service_uri, module.orchestrator-lb-global-lb-backend.apphub_service_uri, [module.orchestrator-db-postgresql.apphub_service_uri], [module.orchestrator-cache-redis.apphub_service_uri], [module.ai-agent-orchestrator.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-gen-lang-client-0592741070" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "gen-lang-client-0592741070"
  disable_services_on_destroy = false
  activate_apis               = []
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "gen-lang-client-0592741070"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudresourcemanager.googleapis.com"]
}
