
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "orchestrator-lb-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.orchestrator-lb-global-lb-frontend.external_ip
}
output "orchestrator-lb-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.orchestrator-lb-global-lb-frontend.external_ipv6_address
}
output "orchestrator-lb-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.orchestrator-lb-global-lb-frontend.ip_address_internal_managed_http
}
output "orchestrator-lb-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.orchestrator-lb-global-lb-frontend.ip_address_internal_managed_https
}
output "orchestrator-cache-redis_host" {
  description = "The IP address of the instance."
  value       = module.orchestrator-cache-redis.host
}
output "orchestrator-cache-redis_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.orchestrator-cache-redis.port
}
output "ai-agent-orchestrator_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-agent-orchestrator.service_uri
}
