"""Composable code generators that reuse Kai's knowledge."""
from __future__ import annotations

import textwrap
from dataclasses import dataclass
from datetime import datetime
from typing import Iterable, List, Optional

from .adapter import Adapter


@dataclass
class FunctionSpec:
    name: str
    docstring: str
    body: str


class Synthesizer:
    """Generate scaffolds that follow Kai's architecture guidelines."""

    def __init__(self, adapter: Optional[Adapter] = None) -> None:
        self.adapter = adapter or Adapter()

    # ------------------------------------------------------------------
    def compose_typescript_module(self, name: str, functions: Iterable[FunctionSpec]) -> str:
        """Create a ready-to-save TypeScript module."""

        header = (
            "// Auto-generated by Kai's Synthesizer\n"
            f"// Module: {name}\n"
            f"// Generated at: {datetime.utcnow().isoformat()}Z\n\n"
        )
        blocks: List[str] = []
        for fn in functions:
            body = textwrap.indent(fn.body.strip("\n"), "    ")
            block = (
                f"/**\n * {fn.docstring}\n */\n"
                f"export function {fn.name}() {{\n{body}\n}}\n"
            )
            blocks.append(block)
        return self.adapter.normalise(header + "\n".join(blocks))

    # ------------------------------------------------------------------
    def compose_react_hook(self, name: str, responsibilities: List[str]) -> str:
        """Create a lightweight React hook template."""

        doc_lines = "\n".join(f" * - {item}" for item in responsibilities)
        body = (
            f"/**\n * {name} hook responsibilities:\n{doc_lines}\n */\n"
            f"export function {name}() {{\n"
            "  const state = React.useRef({});\n"
            "  // TODO: implement hook behaviour\n"
            "  return state.current;\n"
            "}}\n"
        )
        return self.adapter.normalise("import * as React from 'react';\n\n" + body)

    # ------------------------------------------------------------------
    def compose_markdown_brief(self, title: str, sections: List[tuple[str, str]]) -> str:
        """Generate a markdown report from semantic sections."""

        lines = [f"# {title}", ""]
        for heading, content in sections:
            lines.extend([f"## {heading}", content.strip(), ""])
        return self.adapter.adapt_markdown("\n".join(lines))


__all__ = ["Synthesizer", "FunctionSpec"]
